### ISSUE TITLE
WIN+D

### ISSUE THREAD

**Issue by ThiloL** [tip2tail/t2tWinFormAppBarLib#3]
WIN+D hides the Appbar. That shouldn't be the case.
?

**Comment by tip2tail** [comment]
Agreed that seems odd - I will see what can be done about that!

**Comment by ThiloL** [comment]
&#128077;

**Comment by tip2tail** [comment]
@ThiloL 

This has now been fixed.  Please update to NuGet package v1.2.1
https://www.nuget.org/packages/tip2tail.WinFormAppBarLib/1.2.1

Please note the changes in the documentation - this feature requires you to add additional code to enable.

Thanks for the bug report.

**Comment by ThiloL** [comment]
@tip2tail Nice done, **but** with this feature on, a menu on the AppBar will not work anymore (get's no focus).  If i don't use "PreventShowDesktop" menu still works.

**Comment by tip2tail** [comment]
Can you log a new issue please with an example? I'm not sure if it can be
resolved or not.

There are other app bars I have on my system, created by others for things
such as telephone integration. These all hide with show desktop, so perhaps
that is just "the way it is".

We shall see...
